version: '1.0'
services:
  app:
    build: .
    image: app-profiler-1.0.0
    container_name: app
    environment:
      DATABASE_URL: jdbc:mysql://db:3306/profiler-db
      DATABASE_PASSWORD: 1234
      DATABASE_USERNAME: root
      IMAGES_STORAGE_FOLDER: /var/our_image_storage
      JWT_SECRET_PHRASE: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
      CORS_ALLOWED_ORIGINS: none
      CORS_ALLOWED_METHODS: none
    ports:
      - "8080:8080"
    volumes:
      - "/var/our_image_storage:/var/our_image_storage"
    depends_on:
      - db
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: profiler-db
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db: